site_name: SIMPLE

plugins:
  - mkdocs-jupyter:
    include_source: True
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false
            show_root_heading: false

nav:
    - Home: index.md
    - User Guide: user-guide.md
    - API:
      - simple: api/simple.md
      - simple.ccsne: api/ccsne.md
      - simple.norm: api/norm.md
    - About:
          - License: license.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
