name: Create docs
on:
  push:
    branches:
      - master
jobs:
  copyexamples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Copy examples
        run: cp ./notebooks/*ipynb ./docs/examples/
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - run: pip install mkdocs mkdocs-gen-files pymdown-extensions mkdocstrings-python mkdocs-jupyter
      - run: mkdocs gh-deploy --force --clean --verbose
