name: Prepare docs branch
on:
  push:
    branches:
      - master
jobs:
  copyexamples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Copy examples
        run: cp ./notebooks/*ipynb ./docs/examples/
      - name: Commit
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add ./docs/examples/.
          git commit -a -m "Moved notebooks"
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: docs
