name: Prepare docs
on:
  push:
    branches:
      - master
jobs:
  copyexamples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Copy examples
        run: cp ./notebooks/*ipynb ./docs/examples/
      - name: Commit
        run: git commit -a
      - name: Push
        uses: ad-m/github-push-action@docs
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
